
import javax.swing.JOptionPane;
import javax.swing.*;   // For JFrame, JLabel, JButton, JFileChooser, ImageIcon
import java.awt.*;      // For Image
import java.io.File;    // For File class

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class UserProfileJFrame extends javax.swing.JFrame {
    public boolean isValidEmail(String email) {
    return email != null && email.contains("@") && email.contains(".");
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserProfileJFrame.class.getName());

    /**
     * Creates new form UserProfileJFrame
     */
    public UserProfileJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        userProfilePanel = new javax.swing.JPanel();
        userProfileFormLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        lastNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        emailNameLabel = new javax.swing.JLabel();
        noPhotojLabel = new javax.swing.JLabel();
        uploadPhotojButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        userProfilePanel.setBackground(new java.awt.Color(204, 204, 255));

        userProfileFormLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userProfileFormLabel.setText("User Profile Form");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        firstNameLabel.setText("First Name:");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ageLabel.setText("Age:");

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderLabel.setText("Gender:");

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maleRadioButton.setText("Male");
        maleRadioButton.setActionCommand("Male");

        genderButtonGroup.add(femaleButton);
        femaleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femaleButton.setText("Female");
        femaleButton.setActionCommand("Female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        genderButtonGroup.add(submitButton);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastNameLabel.setText("Last Name:");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phoneNumberLabel.setText("Phone Number:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });

        emailNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailNameLabel.setText("Email:");

        noPhotojLabel.setBackground(new java.awt.Color(255, 255, 255));
        noPhotojLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noPhotojLabel.setForeground(new java.awt.Color(255, 255, 255));
        noPhotojLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        noPhotojLabel.setPreferredSize(new java.awt.Dimension(60, 80));

        uploadPhotojButton.setText("Upload Photo");
        uploadPhotojButton.setBorder(null);
        uploadPhotojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPhotojButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userProfilePanelLayout = new javax.swing.GroupLayout(userProfilePanel);
        userProfilePanel.setLayout(userProfilePanelLayout);
        userProfilePanelLayout.setHorizontalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userProfilePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(userProfilePanelLayout.createSequentialGroup()
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(userProfilePanelLayout.createSequentialGroup()
                                .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(firstNameTextField))
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userProfilePanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(phoneNumberLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userProfilePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameLabel)
                                .addGap(12, 12, 12))))
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(femaleButton)
                            .addGroup(userProfilePanelLayout.createSequentialGroup()
                                .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailNameLabel))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userProfilePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(userProfileFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(lastNameTextField)
                            .addComponent(emailTextField))
                        .addGap(65, 65, 65))
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uploadPhotojButton)
                            .addComponent(noPhotojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userProfilePanelLayout.setVerticalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(noPhotojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(userProfileFormLabel)))
                .addGap(1, 1, 1)
                .addComponent(uploadPhotojButton)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLabel))
                        .addGap(9, 9, 9)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(maleRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleButton))
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailNameLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProfilePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
        
        try{
            // Declare variables for user inputs
            String firstName;
            String lastName;
            int age;
            String email;
            String phonenumber;
            String gender;
    
    // Extract and store user's name from nameTextField
        firstName = firstNameTextField.getText();
        lastName  = lastNameTextField.getText();
        
//        Check name validity
        if(firstName.isBlank()) {
             JOptionPane.showMessageDialog(rootPane, "Invalid first name provided!", "errorTitle", JOptionPane.ERROR_MESSAGE);
             return;
        }
             if(lastName.isBlank()){
             JOptionPane.showMessageDialog(rootPane, "Invalid last name provided!", "errorTitle", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        // Extract and store user's age and gender from components
           age = Integer.parseInt(ageTextField.getText());
           gender = genderButtonGroup.getSelection().getActionCommand();
           
           if (gender.equals("Male")){
              gender = "Male";
           }
           
           if (gender.equals("Female")){
               gender = "Female";
           }
        
//        Check age validity
        if (age < 18){
             JOptionPane.showMessageDialog(rootPane, "Invalid age provided", "errorTitle", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        // Extract and store user's phone number from components
           phonenumber = phoneNumberTextField.getText();
           
//         check phonenumber validity
            if (phonenumber.length() < 10|| phonenumber.length() > 15){
//            System.out.println("Phone number must be between 10 and 15 digits.");
            JOptionPane.showMessageDialog(rootPane, "Phone number must be between 10 and 15 digits.", "errorTitle", JOptionPane.ERROR_MESSAGE);
            return;
            }
            
            if(phonenumber.isEmpty()){
                   JOptionPane.showMessageDialog(rootPane, "Phone number is required.", "errorTitle", JOptionPane.ERROR_MESSAGE);
        }
            
           // Extract and store user's email from components
              email = emailTextField.getText();
           
//           Check validity of email 
            if (email == null || email.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Email is required!", "errorTitle", JOptionPane.ERROR_MESSAGE);
            return;
        }

            if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(rootPane, "Invalid email format!", "errorTitle", JOptionPane.ERROR_MESSAGE);
            return;
        }
//      Create a variable for success message \\
        String successMessage = "firstName:" + firstName
        + "\nlastName:" + lastName
        + "\nAge:" + age
        + "\ngender: " + gender
        + "\nphonenumber:" + phonenumber
        + "\nemail: " + email;
                
         JOptionPane.showMessageDialog(rootPane, "successMessage", "Success!", JOptionPane.ERROR_MESSAGE);
         
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Invalid age provided", "errorTitle", JOptionPane.ERROR_MESSAGE);
//                System.out.println("Error: Invalid age provided");
        } catch (NullPointerException e) {
             JOptionPane.showMessageDialog(rootPane, "No gender selected", "errorTitle", JOptionPane.ERROR_MESSAGE);
//                        System.out.println("Error: No gender selected");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid phone number!", "Error", JOptionPane.ERROR_MESSAGE);
    
}
       
        
        }
        

    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

    }//GEN-LAST:event_submitButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void uploadPhotojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPhotojButtonActionPerformed
        // TODO add your handling code here:
        
   public class UserProfileForm extends JFrame {                                                
   private JLabel photoLabel;
    private JButton uploadButton;
   
    public UserProfileForm() {
        setTitle("User Profile");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new FlowLayout());

        // Label for photo
        photoLabel = new JLabel("No Photo");
        photoLabel.setPreferredSize(new Dimension(150, 150));
        photoLabel.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        // Upload button
        uploadButton = new JButton("Upload Photo");
        uploadButton.addActionListener(e -> uploadPhoto());

        add(photoLabel);
        add(uploadButton);

        setVisible(true);
    }

     private void uploadPhoto() {
        JFileChooser fileChooser = new JFileChooser();
        int option = fileChooser.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(file.getAbsolutePath());

            // Resize image to fit the label
            Image img = icon.getImage().getScaledInstance(
                            photoLabel.getWidth(),
                            photoLabel.getHeight(),
                            Image.SCALE_SMOOTH);

            photoLabel.setText(""); // Remove "No Photo"
            photoLabel.setIcon(new ImageIcon(img));
        }
    }

 
 
    }//GEN-LAST:event_uploadPhotojButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel emailNameLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel noPhotojLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton uploadPhotojButton;
    private javax.swing.JLabel userProfileFormLabel;
    private javax.swing.JPanel userProfilePanel;
    // End of variables declaration//GEN-END:variables



